// This file is auto-generated by nextjs-studio.
// Do not edit manually — re-run `npx nextjs-studio --generate-types` to update.

// Branded scalar types — structurally strings/numbers but semantically distinct.
declare const __brand: unique symbol;
type Brand<T, B extends string> = T & { readonly [__brand]: B };

export type Email     = Brand<string, 'Email'>;
export type HttpUrl   = Brand<string, 'HttpUrl'>;
export type ISODate   = Brand<string, 'ISODate'>;
export type MediaPath = Brand<string, 'MediaPath'>;
export type ID        = Brand<string, 'ID'>;
export type Slug      = Brand<string, 'Slug'>;

/** Data shape for the "agenda" collection. */
export interface AgendaEntry {
  titulo: string;
  slug: string;
  descricao: string;
  startsAt: Date;
  endsAt: Date;
  trilha: string;
  tipo: string;
  status: string;
  order: number;
}

/** Data shape for the "codigo-de-conduta" collection. */
export interface CodigoDeCondutaEntry Record<string, unknown>

/** Data shape for the "cotas" collection. */
export interface CotasEntry {
  nome: string;
  label: string;
  beneficios: Array<Record<string, unknown>>;
  featured: boolean;
  disponivel: boolean;
  order: number;
}

/** Data shape for the "ctf" collection. */
export interface CtfEntry {
  titulo: string;
  texto: string;
  formato: string;
  premiacao: string;
  linhas: Array<{
    kind: string;
    texto: string;
  }>;
}

/** Data shape for the "edicoes" collection. */
export interface EdicoesEntry {
  ano: number;
  tema: string;
  local: string;
  publico: string;
  resumo: string;
  albumUrl: string;
  status: string;
}

/** Data shape for the "equipe" collection. */
export interface EquipeEntry {
  nome: string;
  slug: string;
  papel: string;
  url: HttpUrl;
  logo: string;
  order: number;
}

/** Data shape for the "faq" collection. */
export interface FaqEntry Record<string, unknown>

/** Data shape for the "fatos" collection. */
export interface FatosEntry {
  valor: string;
  label: string;
}

/** Data shape for the "ingressos" collection. */
export interface IngressosEntry {
  nome: string;
  slug: string;
  lote: number;
  preco: number;
  parcelas: number;
  descricao: string;
  validThrough: Date;
  ctaUrl: HttpUrl;
  featured: boolean;
  order: number;
}

/** Data shape for the "links" collection. */
export interface LinksEntry Record<string, unknown>

/** Data shape for the "navegacao" collection. */
export interface NavegacaoEntry {
  label: string;
  href: string;
  grupo: string;
  noMenu: boolean;
}

/** Data shape for the "palestrantes" collection. */
export interface PalestrantesEntry Record<string, unknown>

/** Data shape for the "parceiros" collection. */
export interface ParceirosEntry {
  nome: string;
  slug: string;
  url: HttpUrl;
  order: number;
}

/** Data shape for the "patrocinadores" collection. */
export interface PatrocinadoresEntry {
  nome: string;
  slug: string;
  logo: string;
  url: HttpUrl;
  cota: string;
  order: number;
}

/** Data shape for the "settings" collection. */
export interface SettingsEntry {
  eventStartDate: Date;
  eventEndDate: Date;
  eventDisplayDate: string;
  venueName: string;
  venueAddress: string;
  venueMapUrl: HttpUrl;
  ticketsUrl: HttpUrl;
  volunteersDeadline: ISODate;
  cfpDeadline: string;
  sections: {
    fatos: boolean;
    sobre: boolean;
    edicoes: boolean;
    agenda: boolean;
    ctf: boolean;
    palestrantes: boolean;
    ingressos: boolean;
    participe: boolean;
    patrocinio: boolean;
    parceiros: boolean;
    local: boolean;
    faq: boolean;
  };
}

/** Data shape for the "sobre" collection. */
export interface SobreEntry {
  titulo: string;
  texto: string;
  origemTitulo: string;
  origemTexto: string;
  pilares: Array<Record<string, unknown>>;
}

// Augment both entry points so queryCollection() is fully typed regardless of import path.
declare module 'nextjs-studio' {
  interface CollectionTypeMap {
    "agenda": AgendaEntry;
    "codigo-de-conduta": CodigoDeCondutaEntry;
    "cotas": CotasEntry;
    "ctf": CtfEntry;
    "edicoes": EdicoesEntry;
    "equipe": EquipeEntry;
    "faq": FaqEntry;
    "fatos": FatosEntry;
    "ingressos": IngressosEntry;
    "links": LinksEntry;
    "navegacao": NavegacaoEntry;
    "palestrantes": PalestrantesEntry;
    "parceiros": ParceirosEntry;
    "patrocinadores": PatrocinadoresEntry;
    "settings": SettingsEntry;
    "sobre": SobreEntry;
  }
}
declare module 'nextjs-studio/server' {
  interface CollectionTypeMap {
    "agenda": AgendaEntry;
    "codigo-de-conduta": CodigoDeCondutaEntry;
    "cotas": CotasEntry;
    "ctf": CtfEntry;
    "edicoes": EdicoesEntry;
    "equipe": EquipeEntry;
    "faq": FaqEntry;
    "fatos": FatosEntry;
    "ingressos": IngressosEntry;
    "links": LinksEntry;
    "navegacao": NavegacaoEntry;
    "palestrantes": PalestrantesEntry;
    "parceiros": ParceirosEntry;
    "patrocinadores": PatrocinadoresEntry;
    "settings": SettingsEntry;
    "sobre": SobreEntry;
  }
}
